#!/bin/bash

REALTIMEKIT_DIRECTORY=$1
REALTIMEKIT_UI_DIRECTORY=$(pwd)

if [[ -z $REALTIMEKIT_DIRECTORY ]]
then
  echo "Usage: ./fastdev <path_to_web_core>"
  exit 1
fi

REALTIMEKIT_DIRECOTRY=$(readlink -f $REALTIMEKIT_DIRECTORY)

npm link $REALTIMEKIT_DIRECTORY/realtimekit-wrapper --workspace packages/core

npm run dev
